x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  https-portal:
    <<: *restart_policy
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'sentry.cloudnativedays.jp -> http://nginx:80'
      STAGE: 'production' # Don't use production until staging works
    volumes:
      - https-portal-data:/var/lib/https-portal
    depends_on:
      - nginx

volumes:
  https-portal-data:
